services:
  backend:
    image: backend
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - '5000:5000'
  frontend:
    image: frontend
    build:
      context: ./web
      dockerfile: ./Dockerfile
    ports:
      - '5173:5173'
