name: ci-docker

on:
  push:
    branches:
      - 'main'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - 
        name: Get Tag
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      
      - 
        name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }}
      -
        name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: api/
          push: true
          tags: brxvn/avatares-devops-pj1-backend:${{ steps.vars.outputs.sha_short }}

      -
        name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: web/
          push: true
          tags: brxvn/avatares-devops-pj1-frontend:${{ steps.vars.outputs.sha_short }}

  kustomize:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Get Tag
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Checkout GitOps Repo
        uses: actions/checkout@v4
        with:
          repository: whoisbryan/GitOps
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Kustomize 
        uses: imranismail/setup-kustomize@v2
      - run: |
          git config --global user.email "bgonzalez@occ.com.mx"
          git config --global user.name "whoisbryannn"
          cd project-1/avatares-devops-backend
          kustomize edit set image brxvn/avatares-devops-pj1-backend:${{ steps.vars.outputs.sha_short }}
          cd project-1/avatares-devops-frontend
          kustomize edit set image brxvn/avatares-devops-pj1-frontend:${{ steps.vars.outputs.sha_short }}
          git add .
          git commit -m "Set avatares-devops-pj1-backend and frontend image tag to ${{ steps.vars.outputs.sha_short }}"
          git push

